services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 1s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data # Persist database data
    ports:
      - ${DB_PORT}:5432 # Map PostgresSQL port
  
  api:
    image: moj124/chat-api:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000

volumes:
  db-data: # Define a named volume for PostgreSQL data persistence