name: Node CI with Api

on:
  push:
    branches:
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2

      - 
        name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - 
        name: Install cleanly dependencies
        run: npm ci

      - 
        name: Run tests
        run: npm test

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: moj124/chat-api:latest