name: Node CI with Api

on:
  push:
    branches:
      - '**'


jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - 
        name: Install cleanly dependencies
        run: npm ci

      - 
        name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v25
        with:
          config_path: "../eslint.config.mjs"
          extra_args: "--max-warnings=0"

      - 
        name: Run tests
        run: npm test

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          target: production
          push: true
          tags: moj124/chat-api:latest